#!/bin/bash
# run sql command file on postgres db
# usage:
#   shell/migrate test 000-init.sql
#   etc
# note: this assumes postgres is running

#. convert to node

SETUP=$1   # eg test
MIGRATION=$2   # eg 000-init.sql

# this should match docker-compose file
CONTAINER=timescaledb

ENV_FILE=setups/.env
SQL_FILE=setups/$SETUP/migrations/$MIGRATION

# first line reads .env file variables
# see https://stackoverflow.com/a/20909045/243392
export $(grep -v '^#'  $ENV_FILE | xargs) \
  && cat $SQL_FILE | docker exec -i $CONTAINER sh -c "psql -U $PGUSER"
