#!/usr/bin/env node

// build and optionally deploy site
// usage: shell/site

// note: must use require instead of import, else must add .js extension to file
//. couldn't we just use execSync from child-process?
const shell = require('shelljs')

const deploy = process.argv[2] === '-d' || process.argv[2] === '--deploy'

//npm run --silent --prefix packages/neomem-domain-site build
const cmd = `node packages/neomem-domain-site/src/site.js > site/index.html`
shell.exec(cmd)

if (deploy) {
  const cmd1 = `npm --prefix site run build`
  shell.exec(cmd1)

  const cmd2 = `firebase deploy`
  shell.exec(cmd2)
}
